In [5]:
import numpy as np
vetor = np.array([1,2,3,4,5,6,7,8])
print(vetor)

modulo = np.linalg.norm(vetor)
print(modulo)

[1 2 3 4 5 6 7 8]


In [9]:
#produto de vetor bidimencional

import numpy as np
vetor2 = np.array([-55,12])
print (vetor2)
modulo2 = np.linalg.norm(vetor2)
print(modulo2)

[-55  12]
56.293871780150276


In [10]:
#produto de vetor tridimencional

import numpy as np
vetor3 = np.array([11,-23,-4])
print(vetor3)
modulo3 = np.linalg.norm(vetor3)
print(modulo3)

[ 11 -23  -4]
25.80697580112788


In [12]:
from re import sub
import numpy as np
u = np.array([-3,-5])
v = np.array([6,27])

soma = u + v
print(f'A soma dos vetores é: {soma}')

subtracao = u - v
print(f'A subtração dos vetores é: {subtracao}')

multp = 9 * u
print(f'A multiplicação dos vetores é: {multp}')

multpFra = (1/3) * v
print(f'A multiplicação dos vetores é: {multpFra}')

A soma dos vetores é: [ 3 22]
A subtração dos vetores é: [ -9 -32]
A multiplicação dos vetores é: [-27 -45]
A multiplicação dos vetores é: [2. 9.]


In [18]:
#Operações

import numpy as np
u = np.array([2,(5/3)])
v = np.array([-1,7])

soma = u + v
print(f"A soma dos vetores é : {soma}")

subtracao = u - v
print(f"A soma subtração dos vetores é : {subtracao}")

multiplicacao = 3 * u
print(f"A multiplicação dos vetores é : {multiplicacao}")

multiplicacaoFra = (1/5) * v
print(f"A multiplicação dos vetores por fração é : {multiplicacaoFra}")

A soma dos vetores é : [1.         8.66666667]
A soma subtração dos vetores é : [ 3.         -5.33333333]
A multiplicação dos vetores é : [6. 5.]
A multiplicação dos vetores por fração é : [-0.2  1.4]


In [33]:
#Resultante dos vetores

import numpy as np
import math as mt

a = np.array([-2,3])
b = np.array([7,4])

#r*r = a*a + b*b + 2a.b. cos(135º)

#Modelo dos vetores
moduloA = np.linalg.norm(a)
moduloB = np.linalg.norm(b)

print(f"A = {moduloA}")
print(f"B = {moduloB}")

#Cosseno de 135º
cos135 = mt.cos(mt.radians(135))


r2 = (moduloA**2)+(moduloB**2)+(2*moduloA*moduloB*cos135)
r = mt.sqrt(r2)
print(r)

A = 3.605551275463989
B = 8.06225774829855
6.073745995496607


In [37]:
#Produto escalar

import numpy as np

a = np.array([5,4,2])
b = np.array([1,3,-12])

#bibliotaca para calcular o produto escalar
produto = np.dot(a,b)
print(produto)

-7


In [1]:
import numpy as np
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]]) #cada [] é uma linha da matriz
print(matriz)
matriz.shape #shape mostra o tamanho da matriz

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [3]:
import numpy as np
a = np.random.rand(2,2)# random rand gera valor
print(f"A matriz A é: {a}")

b = np.random.rand(3,4)
print(f"A matriz B é: {b}")

A matriz A é: [[0.60859186 0.82927983]
 [0.09125398 0.50400507]]
A matriz B é: [[0.68017277 0.31514121 0.19265128 0.89086636]
 [0.72108951 0.76653632 0.89054197 0.24187985]
 [0.99811572 0.78759393 0.14220196 0.47648342]]


In [4]:
#Matriz de identidade

import numpy as np
I = np.identity(3)#identity gera a matriz de identidade
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
#Matriz trsnposta

import numpy as np

A = np.random.rand(3,2)#linha x coluna

A_Transpose = np.transpose(A)#trsnpose serve para gerar uma matriz transposta

print(A)
print("")
print(A_Transpose)

[[0.02296441 0.21661423]
 [0.63456144 0.55607702]
 [0.07988291 0.38911271]]

[[0.02296441 0.63456144 0.07988291]
 [0.21661423 0.55607702 0.38911271]]


In [13]:
#Operação com Matrizes

import numpy as np

a = np.array([[0,-9], [-5,8], [-15,13]])

b = np.array([[3,-19], [-4,7], [14,-11]])

c = a + b #soma

d = a - b #subtração

e = a * 15 #multiplicação

print(f"A soma das matrizes é:")
print(c)
print("")
print(f"A subtração das matrizes é:")
print(d)
print("")
print(f"A multiplicação das matrizes é:")
print(e)

A soma das matrizes é:
[[  3 -28]
 [ -9  15]
 [ -1   2]]

A subtração das matrizes é:
[[ -3  10]
 [ -1   1]
 [-29  24]]

A multiplicação das matrizes é:
[[   0 -135]
 [ -75  120]
 [-225  195]]


In [1]:
#multiplicação entre matrizes

import numpy as np

a = np.array([[1,-3,5], [8,0,3]])
b = np.array([[2,4], [6,10], [1,5]])

c = np.matmul(a,b)

print(f"O resultado da mutiplicação entre as matrizes é:")
print(c)

O resultado da mutiplicação entre as matrizes é:
[[-11  -1]
 [ 19  47]]


In [19]:
# Determinante de matriz

import numpy as np

a = np.array([[1,9,5], [3,7,8], [10,4,2]])

detA = np.linalg.det(a)#lenalg para calcular a algebra e Det para usar infor que é determiante

print("A determinante a matriz é")
print(detA)

A determinante a matriz é
358.0


In [21]:
import numpy as np
import math as mt

a = np.array([[2,5,-3], [1,4,7], [-2,0,6]])

b = np.array([[mt.sqrt(2),2,1], [-1,mt.sqrt(3),3],[3,2,mt.sqrt(6)]])

detA = np.linalg.det(a)
detB = np.linalg.det(b)

print(detA)
print("")
print(detB)

-76.0

13.217545688621149
